fixtures:
  repositories:
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    sumo: "#{source_dir}"
  forge_modules:
     stdlib:
       repo: "puppetlabs/stdlib"
       ref: "4.12.0"